### ISSUE TITLE
[feature] luap source ~/.config/luaprompt/init.lua at begining

### ISSUE THREAD

**Issue by Freed-Wu** [dpapavas/luaprompt#18]
It allow users to use `init.lua` to customize the prompts. Just add some code before <https://github.com/dpapavas/luaprompt/blob/master/luap.lua#L210>

And why not when `prompt.prompts[1]`, `prompt.prompts[2]` is a function, calculate the return value as the true prompt before print prompt? It allows prompts change according to CWD / time.

**Comment by dpapavas** [comment]
>It allow users to use init.lua to customize the prompts. Just add some code before https://github.com/dpapavas/luaprompt/blob/master/luap.lua#L210

If I understand you correctly, you want something like a bashrc file, but for `luap`.  I haven't dabbled in Lua for a while, but I think `init.lua` is generally associated with initialization scripts for modules themselves (it's in the default module search path for instance), so perhaps something like `luapromptrc.lua` might be a better name.

More importantly, I wonder how it should work.  One approach would be that it would be just executed and you can then require the `prompt` module from there and set your variables.  Another approach would be that you would set your settings in there as global variables, e.g.:
```
   name = 'lua'
   prompts = {'>  ', '>> '}
   colorize = true
   history = os.getenv('HOME') .. '/.lua_history'
```
and the script would be evaluated and any values set in there, would override the defaults.  I think I like this second approach better, what do you think?

Also, I wonder whether this should perhaps be done at the module level, so that this rc file affects all uses of `luaprompt` in the system, instead of just `luap`.

**Comment by Freed-Wu** [comment]
> I wonder whether this should perhaps be done at the module level, so that this rc file affects all uses of luaprompt in the system, instead of just luap.

I know readline has a config file named `~/.inputrc`. It works for all programs using readline, while user can set individual config for some specific program by `if`

```readline
# work for all programs using readline
set blink-matching-paren on
set colored-completion-prefix on
set colored-stats on
...
# work only for sdcv, define a hotkey `<C-G>`
$if sdcv
  "\x07": "\x15-1\n"
$endif
# work only for reply, define a hotkey `<C-X><C-E>`
$if reply
  "\x18\x05": "#e\n"
$endif
```

I think `luap` can work for all uses of luaprompt, but user can use `if` to decide specific behaviour for different use.

> I wonder how it should work

I hope this program is more flexible. For example, like zsh, user can define
their plugin to define prompt string like
[p10k](https://github.com/romkatv/powerlevel10k). Maybe `require 'prompt'` can
be more powerful.

> why not when prompt.prompts[1], prompt.prompts[2] is a function

Because a prompt string usually contains time, CWD, ... information, so I think
use a function to get these infromation is necessary.

![img](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png)

In addition, I want to know can it work for other lua? Such as luatex has a
`texlua`, many latex tools such as `texdoc`, `l3build` use `#!/usr/bin/env texlua`. However,
`texlua` doesn't have a REPL. If it has a REPL, it will be convenient for debug
and develop latex tools.

**Comment by dpapavas** [comment]
> I think luap can work for all uses of luaprompt, but user can use if to decide specific behaviour for different use.

While it may be possible to supply the "program name" for instance (which can be set with `luap_setname`) to the rc script, so that constructs such as `if name == "someprogram" then ... end` could be used, I think this would be overkill for now.  I don't think use of `luaprompt` is so widespread that one is likely to have multiple programs using it installed, each needing a different configuration.  We can consider it if such a need actually arises.

> hope this program is more flexible. For example, like zsh, user can define their plugin to define prompt string like [p10k](https://github.com/romkatv/powerlevel10k).

Well, a user will be a ble to define a "plugin" of sorts, by creating an rc file.  Whether such fancy prompts will be possible is another issue.  Perhaps it will simply be a matter of specifying prompt strings containing the proper ANSI color escape sequences and UTF characters.  At any rate, fancy colored prompts aren't really a vital feature for a simple Lua REPL prompt.

> In addition, I want to know can it work for other lua?
I see no way of forcing existing tools to have a `luaprompt` REPL.  If a REPL would be useful with `luatex`, it would have to be implemented in `luatex`, optionally using `luaprompt`.  If you think something like that would be useful, consider opening an feature request issue on their tracker.

In the meantime, I'll try to put together an implementation for simple "luapromptrc.lua" support and also look into making the prompts support function values when I find some spare time.

**Comment by Freed-Wu** [comment]
What is the progress? :smile:

**Comment by dpapavas** [comment]
I've just pushed branch [issue-118](https://github.com/dpapavas/luaprompt/tree/issue-118) with an implementation.  As for configuration of the prompt for `luap`, I've simply made it read an rc file on startup, named `~/.luarc`, to keep the similarity with `bashrc`/`bash_history`.  You can import the prompt module and set any values from there. See the README for an example.

I've also allowed passing functions to `prompt.prompts`, to make the prompts dynamic.  It works as you'd expect; again see the README for an example.

I haven't been using Lua (and hence `luaprompt`) for quite some time now, so I'm not in the best position to test this.  As far as I can see, it seems to work fine.  Please check out the branch and do some testing of your own and let me know if it's ok.

**Comment by Freed-Wu** [comment]
I advise:

```diff
diff --git a/Makefile b/Makefile
index 1b804ea..35c4cc6 100644
--- a/Makefile
+++ b/Makefile
@@ -9,7 +9,9 @@ MAN1DIR = $(MANDIR)/man1
 # libraries.
 
 LUA_CFLAGS = $(shell pkg-config --cflags lua${VERSION})
+READLINE_CFLAGS = $(shell pkg-config --cflags readline)
 LUA_LDFLAGS = $(shell pkg-config --libs-only-L lua${VERSION})
+READLINE_LDFLAGS = $(shell pkg-config --libs-only-L readline)
 
 CFLAGS = -g -fPIC
 CFLAGS += -Wall -Wextra -Wno-unused-parameter -DHAVE_ASPRINTF
@@ -83,7 +85,7 @@ INSTALL=/usr/bin/install
 all: prompt.so
 
 prompt.so: module.c prompt.c prompt.h
-	$(CC) -o prompt.so -shared ${CFLAGS} ${LUA_CFLAGS} module.c prompt.c ${LDFLAGS} ${LUA_LDFLAGS}
+	$(CC) -o prompt.so -shared ${CFLAGS} ${LUA_CFLAGS} ${READLINE_CFLAGS} module.c prompt.c ${LDFLAGS} ${LUA_LDFLAGS} ${READLINE_LDFLAGS}
 
 dist: luap
 	if [ -e /tmp/prompt ]; then rm -rf /tmp/prompt; fi
```

**Comment by Freed-Wu** [comment]
And I think `~/.luarc` is easy to let users mistake it can work for `lua`, maybe `~/.luapromptrc.lua` or `~/.config/luaprompt/conf.lua` is better. `.lua` is only for editors to let them know this file should be highlighted as lua syntax.

**Comment by Freed-Wu** [comment]
It looks good:

![Screenshot from 2023-07-22 17-38-20](https://github.com/dpapavas/luaprompt/assets/32936898/c4c6e13c-3b39-4315-b09b-206a1a7783ea)

> I haven't been using Lua

Can you add me to collaborators?

**Comment by Freed-Wu** [comment]
I have packaged this package to [my Linux distribution](https://github.com/NixOS/nixpkgs/pull/244830).
It can avoid declaring many variables: `luarocks install luaprompt HISTORY_INCDIR=~/.local/state/nix/profile/include READLINE_INCDIR=~/.local/state/nix/profile/include HISTORY_LIBDIR=/run/current-system/sw/lib READLINE_LIBDIR=/run/current-system/sw/lib`

**Comment by dpapavas** [comment]
> And I think `~/.luarc` is easy to let users mistake it can work for `lua`, maybe `~/.luapromptrc.lua` or `~/.config/luaprompt/conf.lua` is better. `.lua` is only for editors to let them know this file should be highlighted as lua syntax.

Agreed, and since the rc file concerns `luap` in particular and not `luaprompt` (as a module), I've changed it to support `~/.luaprc.lua`, or alternatively `~/.config/luaprc.lua`.

> I advise:
> ...

What is the purpose of specifying the Readline-related flags separately?

> Can you add me to collaborators?

If you mean you'd like to be added to the copyright notices, then I'm afraid I can't do that since you haven't contributed any code or documentation.  If you'd like me to create a file like `CONTRIBUTORS` and place your name in there, I'd be happy to do that!

**Comment by Freed-Wu** [comment]
> If you mean you'd like to be added to the copyright notices,

I means I want to merge:

```diff
diff --git a/Makefile b/Makefile
index 1b804ea..35c4cc6 100644
--- a/Makefile
+++ b/Makefile
@@ -9,7 +9,9 @@ MAN1DIR = $(MANDIR)/man1
 # libraries.
 
 LUA_CFLAGS = $(shell pkg-config --cflags lua${VERSION})
+READLINE_CFLAGS = $(shell pkg-config --cflags readline)
 LUA_LDFLAGS = $(shell pkg-config --libs-only-L lua${VERSION})
+READLINE_LDFLAGS = $(shell pkg-config --libs-only-L readline)
 
 CFLAGS = -g -fPIC
 CFLAGS += -Wall -Wextra -Wno-unused-parameter -DHAVE_ASPRINTF
@@ -83,7 +85,7 @@ INSTALL=/usr/bin/install
 all: prompt.so
 
 prompt.so: module.c prompt.c prompt.h
-	$(CC) -o prompt.so -shared ${CFLAGS} ${LUA_CFLAGS} module.c prompt.c ${LDFLAGS} ${LUA_LDFLAGS}
+	$(CC) -o prompt.so -shared ${CFLAGS} ${LUA_CFLAGS} ${READLINE_CFLAGS} module.c prompt.c ${LDFLAGS} ${LUA_LDFLAGS} ${READLINE_LDFLAGS}
 
 dist: luap
 	if [ -e /tmp/prompt ]; then rm -rf /tmp/prompt; fi
```

You should merge issue-18 firstly, otherwise I cannot create a PR for master branch.

**Comment by Freed-Wu** [comment]
> What is the purpose of specifying the Readline-related flags separately?

I use NixOS:

```shell
$ pkg-config --cflags readline
-I/nix/store/16fjk9vr0kdsdl3vad27148c48njjbkl-readline-8.2p1-dev/include
```

If I don't do this, It cannot be built for me.

**Comment by dpapavas** [comment]
> You should merge issue-18 firstly, otherwise I cannot create a PR for master branch.

I've merged my changes to master.  Go ahead and create your PR.

**Comment by Freed-Wu** [comment]
#19
