### ISSUE TITLE
Feature: suggest method names

### ISSUE THREAD

**Issue by starius** [dpapavas/luaprompt#8]
If a user presses TAB after typing "xxx:" or "xxx:yyy" then luaprompt can suggest some methods using information from `getmetatable(xxx).__index` if is is defined and is table.

**Comment by dpapavas** [comment]
This is interesting.  This feature of metatable lookups has been there since version 5.0 and I've never really realized it.  And of course, this concerns more than the table:key() syntax, as it applies to all table key accesses.

The wip branch now supports completing table keys based on __index being a table.  This feature is individualy selectable through the Makefile.  Have a look and let me know what you think.

**Comment by starius** [comment]
It works.
