### ISSUE TITLE
filenames completion closes quotes at directory names

### ISSUE THREAD

**Issue by starius** [dpapavas/luaprompt#9]
```
>  yyy = dofile '/tm
```
TAB
```
>  yyy = dofile '/tmp'
```

It should be `'/tmp`, then `'/tmp/`, but not `'/tmp'`

**Comment by dpapavas** [comment]
I was, in fact, aware of this.  Either readline was not designed for such fancy completion, or I didn't figure out how to use it properly (it's a pretty old library, with a rather bad design and not the best of documentation), in any case, I got hopelessy mixed up trying to convince it to complete file names.  It's one of the few types of completion it does on its own, but I couldn't get it to work with proper quoting and only when it would make sense in Lua (inside strings).  Well, long story short, as it turns out, it was a pretty simple fix.  Check it out in the wip branch.

**Comment by starius** [comment]
It works. Thank you!
